version: 2
jobs:
  test:
    working_directory: ~/chaos
    docker:
      - image: circleci/openjdk
        environment:
    steps:
      - checkout
      - run:
          name: assemble
          command: ./gradlew assemble
      - run:
          name: test
          command: ./gradlew test
      - store_test_results:
          path: "~/chaos/build/test-results"
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
