version: 2
jobs:
  test:
    working_directory: ~/chaos
    docker:
      - image: circleci/openjdk
        environment:
    steps:
      - checkout
      - restore_cache:
          keys:
          - chaos-{{ .Branch }}-{{ checksum "build.gradle" }}
          - chaos-master-{{ checksum "build.gradle" }}
      - run:
          name: compile
          command: ./gradlew assemble compileTestJava
      - save_cache:
          key: chaos-{{ .Branch }}-{{ checksum "build.gradle" }}
          paths:
            - "~/.gradle"
      - run:
          name: test
          command: ./gradlew test
      - store_test_results:
          path: "~/chaos/build/test-results"
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
